SELECT     TOP (100) PERCENT U.FULL_NAME AS SUPERVISORFULLNAME, F.MARKETING_DESCRIPTION AS FACILITYNAME, P.PLANT_DESCRIPTION AS PLANTNAME, 
                      W.WORK_CENTER_DESCRIPTION AS WORKCENTERNAME, U.USER_MASTER_ID, U.FIRST_NAME, U.LAST_NAME, U.ASSOCIATE_NUMBER, 
                      W.WORK_CENTER_MASTER_ID, W.WORK_CENTER, P.PLANT_ID, F.FACILITY_ID, F.FACILITY_ABBREVIATION
FROM         DBO.WORK_CENTER_MASTER_USER_MASTER_LINK AS L INNER JOIN
                      DBO.WORK_CENTER_MASTER AS W ON W.WORK_CENTER_MASTER_ID = L.WORKCENTERMASTERID INNER JOIN
                      DBO.USER_MASTER AS U ON U.USER_MASTER_ID = L.USERMASTERID INNER JOIN
                      DBO.PLANT AS P ON P.PLANT_ID = W.PLANT_ID INNER JOIN
                      DBO.FACILITY AS F ON F.FACILITY_ID = P.FACILITY_ID
ORDER BY F.FACILITY_ID, P.PLANT_ID, W.WORK_CENTER_MASTER_ID